Likelion-backend-IDLE/FindMyDuo

build.gradle
src/main/resources/application.yaml

- .yaml: 기초 환경설정 추가(JPA, Hibernate, jwt, 민감정보 환경변수 추가)
- build.gradle: MySQL 의존성 추가

Conf: MySQL DB 연결 설정

---

build.gradle
src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/dto/SignupDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserLoginRequestDto.java
src/main/java/com/idle/fmd/domain/user/entity/CustomUserDetails.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/repo/UserRepository.java
src/main/java/com/idle/fmd/domain/user/service/CustomUserDetailsManager.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/config/PasswordEncoderConfig.java
src/main/java/com/idle/fmd/global/config/WebSecurityConfig.java
src/main/java/com/idle/fmd/global/error/exception/BusinessException.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
src/main/java/com/idle/fmd/global/error/exception/ExceptionControllerAdvice.java
src/main/resources/application.yaml

Feat: 로그인 기본 기능 구현

---

build.gradle
src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/auth/JwtTokenDto.java
src/main/java/com/idle/fmd/global/auth/JwtTokenFilter.java
src/main/java/com/idle/fmd/global/auth/JwtTokenUtils.java
src/main/resources/application.yaml

closed #13
- application.yaml: jwt 변수 선언
- build.gradle: jwt 의존성 추가
-  jwtTokenUtil: jwt 유효성 검사, 해석, 생성 기능
-  jwt필터, 생성 dto 추가
-  로그인 성공시 jwt 토큰 생성되도록 수정

5 login jwt

---

.gitignore
build.gradle
src/main/java/com/idle/fmd/domain/lol/entity/LolEntity.java
src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/dto/SignupDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserLoginRequestDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserLoginResponseDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserMyPageRequestDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserMyPageResponseDto.java
src/main/java/com/idle/fmd/domain/user/entity/CustomUserDetails.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/repo/UserRepository.java
src/main/java/com/idle/fmd/domain/user/service/CustomUserDetailsManager.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/auth/jwt/JwtTokenFilter.java
src/main/java/com/idle/fmd/global/auth/jwt/JwtTokenUtils.java
src/main/java/com/idle/fmd/global/auth/oauth2/OAuth2SuccessHandler.java
src/main/java/com/idle/fmd/global/auth/oauth2/OAuth2UserServiceImpl.java
src/main/java/com/idle/fmd/global/common/controller/ViewController.java
src/main/java/com/idle/fmd/global/config/PasswordEncoderConfig.java
src/main/java/com/idle/fmd/global/config/WebSecurityConfig.java
src/main/java/com/idle/fmd/global/error/exception/BusinessException.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
src/main/java/com/idle/fmd/global/error/exception/ExceptionControllerAdvice.java
src/main/resources/application.yaml
src/main/resources/templates/login-form.html

- 회원 정보 조회 기능 추가
- 회원 정보 수정 기능 추가
- 회원 탈퇴 기능 추가

Feat: 마이페이지 기본 기능 추가

---

src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/dto/UserMyPageRequestDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserMyPageResponseDto.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/service/CustomUserDetailsManager.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java

- 회원 정보 조회 기능 추가
- 회원 정보 수정 기능 추가
- 회원 탈퇴 기능 추가
- 프로필 이미지 등록 및 변경 기능 추가

Feat: 마이페이지 기능 추가

---

src/main/java/com/idle/fmd/FmdApplication.java
src/main/java/com/idle/fmd/domain/board/controller/BoardController.java
src/main/java/com/idle/fmd/domain/board/dto/BoardCreateDto.java
src/main/java/com/idle/fmd/domain/board/dto/BoardResponseDto.java
src/main/java/com/idle/fmd/domain/board/dto/BoardUpdateDto.java
src/main/java/com/idle/fmd/domain/board/entity/BoardEntity.java
src/main/java/com/idle/fmd/domain/board/repo/BoardRepository.java
src/main/java/com/idle/fmd/domain/board/service/BoardService.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/global/common/entity/BaseTimeEntity.java
src/main/java/com/idle/fmd/global/config/WebSecurityConfig.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java

Feat: 게시판 crud

---

src/main/java/com/idle/fmd/domain/user/entity/CustomUserDetails.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/service/CustomUserDetailsManager.java

- UserEntity
- @Data 삭제
- @Builder @AllArgsConstructor @NoArgsConstructor(access = AccessLevel.PROTECTED) @Getter 추가
- CustomUserDetails -> UserEntity 변환 정적 팩토리 메소드 추가
- 유저 업데이트, 프로필 업데이트 메소드 추가
- CustomUserDetails
- 연관성없는 메소드 삭제
- CustomUserDetailsManager
- UserEntity 리팩토링에 따른 코드 수정 및 기타 가독성을 위한 코드 수정
Close #43

Refactor: Entity 객체 일관성 향상을 위한 Refactoring

---

build.gradle
src/main/java/com/idle/fmd/domain/board/controller/BoardController.java
src/main/java/com/idle/fmd/domain/board/dto/BoardResponseDto.java
src/main/java/com/idle/fmd/domain/board/entity/BoardEntity.java
src/main/java/com/idle/fmd/domain/board/service/BoardService.java
src/main/java/com/idle/fmd/domain/file/entity/FileEntity.java
src/main/java/com/idle/fmd/domain/file/repo/FileRepository.java
src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/dto/UserLoginResponseDto.java
src/main/java/com/idle/fmd/domain/user/entity/CustomUserDetails.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/service/CustomUserDetailsManager.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/auth/jwt/JwtTokenFilter.java
src/main/java/com/idle/fmd/global/auth/jwt/JwtTokenUtils.java
src/main/java/com/idle/fmd/global/common/utils/FileHandler.java
src/main/java/com/idle/fmd/global/common/utils/RedisUtil.java
src/main/java/com/idle/fmd/global/config/WebClientConfig.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java

Feat: 게시판 이미지 기능

---

src/main/java/com/idle/fmd/domain/board/service/BoardService.java
src/main/java/com/idle/fmd/domain/comment/controller/CommentController.java
src/main/java/com/idle/fmd/domain/comment/dto/CommentRequestDto.java
src/main/java/com/idle/fmd/domain/comment/dto/CommentResponseDto.java
src/main/java/com/idle/fmd/domain/comment/entity/CommentEntity.java
src/main/java/com/idle/fmd/domain/comment/repo/CommentRepository.java
src/main/java/com/idle/fmd/domain/comment/service/CommentService.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java

Feat: 댓글 기본 기능 추가, 댓글 Soft Delete, 게시글 삭제 시 관련 댓글 삭제 기능 추가
closed #37

Feat: 댓글 CRUD

---

src/main/java/com/idle/fmd/domain/comment/controller/CommentController.java
src/main/java/com/idle/fmd/domain/comment/dto/CommentRequestDto.java
src/main/java/com/idle/fmd/domain/comment/entity/CommentEntity.java
src/main/java/com/idle/fmd/domain/comment/service/CommentService.java

Refactor: Entity 객체 일관성 향상을 위한 Refactoring,Validated 유효성 검사 추가

Refactor: Entity 객체 일관성 향상을 위한 Refactoring,Validated 유효성 검사 추가

---

src/main/java/com/idle/fmd/domain/board/controller/BoardController.java
src/main/java/com/idle/fmd/domain/board/entity/BoardEntity.java
src/main/java/com/idle/fmd/domain/board/repo/BoardRepository.java
src/main/java/com/idle/fmd/domain/board/service/BoardService.java
src/main/java/com/idle/fmd/domain/user/repo/UserRepository.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java

Feat: 게시글 검색 기능 추가 (제목, 내용, 사용자)

Feat: 게시글 검색 기능 추가 (제목, 내용, 사용자)

---

.github/workflows/github-actions.yml

- github-actions.yml:
- 'main': push, pull_request 시
- 'develop': push, pull_request 시
Close #68

Feat: Github Actions을 사용한 CI/CD 구축용 workflow .yml 파일 추가

---

src/main/java/com/idle/fmd/domain/user/service/UserService.java

- 프로필 이미지 저장 경로 변경
- 불필요한 코드 삭제

Refactor: 마이페이지 프로필 이미지 기능 수정

---

.github/workflows/github-actions.yml
build.gradle
src/main/java/com/idle/fmd/domain/user/controller/UserViewController.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/config/WebSecurityConfig.java
src/main/resources/static/css/main.css
src/main/resources/static/html/navbar.html
src/main/resources/static/js/login.js
src/main/resources/static/js/mypage.js
src/main/resources/static/js/navbar.js
src/main/resources/static/js/signup.js
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/mypage.html
src/main/resources/templates/signup.html

- 홈 화면 (index.html)
- 사이드 바 메뉴 설정
- 회원가입 화면 
- 로그인 화면
- 마이페이지 화면

Feat: 홈, 회원가입, 로그인, 마이페이지 화면 구현

---

.github/workflows/github-actions.yml

주석 처리가 잘못된 코드로 인해 스크립트 명령에서 오류가 났었음.
#74

Fix: make application-dev.yaml 단계에 잘못 된 주석 코드 수정

---

src/main/resources/static/css/style.css
src/main/resources/static/html/header.html
src/main/resources/static/html/navbar.html
src/main/resources/static/js/mypage.js
src/main/resources/static/js/navbar.js
src/main/resources/static/js/signup.js
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/mypage.html
src/main/resources/templates/signup.html

- 부트스트랩 스타일 적용 및 UI 개선
- 홈 화면 (index.html) 
- 회원가입 화면
- 로그인 화면
- 마이페이지 화면
- 마이페이지에서 프로필 이미지 등록을 위한 코드 추가

Design: 부트스트랩 스타일 적용 및 UI 개선

---

src/main/java/com/idle/fmd/domain/matching/controller/MatchingViewController.java
src/main/java/com/idle/fmd/global/config/security/WebSecurityConfig.java
src/main/resources/static/css/matching.css
src/main/resources/static/css/style.css
src/main/resources/static/html/header.html
src/main/resources/static/html/navbar.html
src/main/resources/static/js/matching.js
src/main/resources/static/js/mypage.js
src/main/resources/templates/matching/chat.html
src/main/resources/templates/matching/matching.html

- 네비게이션 바 UI 개선
- 일부 스타일 수정
- 매칭 화면 UI 구현 (전적 부분 추가 구현 필요)
- 매칭 간단한 버튼 이벤트 기능 추가
- 채팅방 화면 UI 구현 (전체적으로 추가 구현 필요)

Design: UI 개선 및 매칭, 채팅방 UI 구현

---

build.gradle
src/main/java/com/idle/fmd/domain/board/service/BoardService.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/config/etc/AwsConfig.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
src/main/java/com/idle/fmd/global/utils/AwsS3Service.java
src/main/java/com/idle/fmd/global/utils/FileHandler.java

기존 로컬환경에 저장하는 방법에서 AWS-S3에 저장하는 방식으로 변경
resolve #91

Feat: 파일 S3 업로드 기능 추가

---

src/main/resources/static/css/style.css
src/main/resources/static/html/header.html
src/main/resources/static/html/navbar.html
src/main/resources/static/js/login.js
src/main/resources/static/js/mypage.js
src/main/resources/static/js/navbar.js

- 로그인 시 로컬스토리지에 accountId와 profileImage 저장
- 사이드 네비게이션 바 UI 수정
- 로고를 누르면 메인 화면으로 가도록 링크 설정

Feat: 로그인 시 로컬스토리지에 accountId, profileImage 저장

---

src/main/java/com/idle/fmd/domain/board/controller/BoardViewController.java
src/main/java/com/idle/fmd/domain/board/dto/BoardResponseDto.java
src/main/resources/static/js/board.js
src/main/resources/templates/board/board.html

자유게시판 
- 삭제
- 좋아요, 즐겨찾기, 신고
- 댓글 작성, 삭제

Feat: 게시글 삭제, 좋아요, 즐겨찾기, 신고, 댓글 화면

---

src/main/resources/static/css/style.css
src/main/resources/templates/board/board-update-form.html
src/main/resources/templates/board/board-write-form.html
src/main/resources/templates/board/board.html

- board.html: 단일 글 조회 페이지 부트스트랩 적용
- board-write-form.html: 글 작성 페이지 부트스트랩 적용
- board-update-form.html: 글 수정 페이지 부트스트랩 적용
- style.css: 게시판 스타일 적용

Design: 게시물 작성, 수정, 단일 글 조회 페이지 부트스트랩 적용

---

src/main/java/com/idle/fmd/domain/user/dto/UserLoginResponseDto.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/resources/static/js/login.js

- UserService: nickname 정보를 가져오기 위한 UserDetail -> CustumUserDetail 클래스 변경
- UserLoginDto: nickname 필드 추가
- login.js: 전달 받은 nickname 값 localStorage에 저장

Refactor: 클라이언트에서 사용자의 nickname 정보 필요성으로 인한 코드 수정

---

src/main/java/com/idle/fmd/global/config/security/WebSecurityConfig.java
src/main/resources/static/css/style.css
src/main/resources/static/js/board-list.js
src/main/resources/templates/board/board-list.html

- WebSecurityConfig 중복 코드 제거
- 보드 전체 조회 페이지 html 파일과 js 파일 분리
- 보드 전체 조회 페이지 부트스트랩 적용
- css 스타일 추가 및 UI 개선

Design: 보드 전체 조회 페이지 부트스트랩 적용

---

.github/workflows/actions-cd.yml
.github/workflows/actions-ci.yml

- [main, develop] 브랜치에 PR 시 CI workflow 실행
- [main, develop] 브랜치에 Merge(push) 시 CD workflow 실행
#117

Refactor: 기존 동시에 작동하던 CI,CD workflow 분리

---

src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/dto/ChangePasswordRequestDto.java
src/main/java/com/idle/fmd/domain/user/dto/UserMyPageRequestDto.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/repo/UserRepository.java
src/main/java/com/idle/fmd/domain/user/service/CustomUserDetailsManager.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
src/main/resources/static/html/header.html
src/main/resources/static/js/board.js
src/main/resources/static/js/mypage.js
src/main/resources/templates/board/board.html
src/main/resources/templates/login.html
src/main/resources/templates/mypage.html

- 마이페이지 일반 정보와 비밀번호 변경 기능 분리
- 닉네임 중복 확인 버튼 기능 추가
- 댓글 삭제 버튼이 댓글 작성자에게만 보이도록 UI 수정
- 로그인 폼에 회원가입 링크 추가

Design: 마이페이지 UI 개선 및 각종 기능 추가

---

src/main/resources/static/css/style.css
src/main/resources/static/html/navbar.html
src/main/resources/static/js/board-bookmark.js
src/main/resources/templates/board/board-bookmark.html
src/main/resources/templates/board/board-list.html
src/main/resources/templates/mypage.html

- board-bookmark.html: 북마크 페이지 부트스트랩 적용
- board-bookmark.js: 토큰 확인 코드 수정
- mypage.html: 북마크 페이지로 이동 가능한 링크 버튼 추가
- board-list.html: 게시판 UI 개선
- navbar.html: 사이드 네비게이션 바에 북마크 링크 삭제
- style.css: 게시판 테이블 스타일 추가

Design: 게시글 북마크 페이지 부트스트랩 적용 및 UI 개선

---

src/main/java/com/idle/fmd/domain/board/service/BoardService.java
src/main/resources/static/js/board.js
src/main/resources/templates/board/board.html

- 게시글이 존재하지 않는 경우 예외처리
- 게시글 작성자가 아닌 경우 신고 버튼 안보이게 처리

Fix: 없는 게시글 조회, 신고

---

build.gradle
src/main/java/com/idle/fmd/domain/matching/DiscordConfig.java
src/main/java/com/idle/fmd/domain/matching/DiscordService.java
src/main/java/com/idle/fmd/domain/matching/MatchingHandler.java
src/main/java/com/idle/fmd/domain/matching/MatchingService.java
src/main/java/com/idle/fmd/domain/matching/MatchingSuccessDto.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java

- 추가된 class
- DiscordConfig: 디스코드연결을 위한 설정값 정의, 디스코드와 연결 및 채널 생성, 삭제 메서드 정의 클래스
- DiscordService: 디스코드 채널생성기능을 사용하기위한 Service 클래스
- 변경된 코드: 디스코드 음성채널 추가로 인한 매칭 수락 후 동작 관련 코드 수정
#109

Feat: Discord Api를 사용해서 매칭 성공시 음성 채널 생성 후 해당 채널 Url 반환 받는 기능 추가

---

.github/workflows/actions-cd.yml
.github/workflows/actions-ci.yml

기존
- CI: 프로젝트 빌드, 도커이미지 생성
- CD: 배포
수정 후
- CI: 프로젝트 빌드, 도커이미지 생성
- CD:  프로젝트 빌드, 도커이미지 생성, 배포

Chore: workflow 코드 수정

---

src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/config/security/WebSecurityConfig.java
src/main/resources/static/css/style.css
src/main/resources/static/js/signup.js
src/main/resources/templates/login.html
src/main/resources/templates/signup.html

- 회원가입 폼에서 각종 help 메시지가 출력되도록 UI 개선
- 모든 폼이 작성됐을 때만 버튼이 눌리도록 수정

Design: 회원가입 폼 UI 개선 및 help 메시지 출력

---

src/main/resources/static/js/mypage.js

Design: 계정 생성날짜 표시방법 변경

---

src/main/java/com/idle/fmd/domain/lol/repo/LolAccountRepository.java
src/main/java/com/idle/fmd/domain/lol/service/LolApiService.java
src/main/resources/static/js/mypage.js

- DB에서 이미 등록된 닉네임을 찾는 것이 아닌 아이디를 찾도록 수정
- 롤 계정 연동 시 알림창 기능 추가
- 닉네임 중복 확인 get 요청 url 수정

Fix: 롤 API 예외 처리 수정 및 마이페이지 프론트 기능 수정

---

src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
src/main/java/com/idle/fmd/global/utils/FileHandler.java

- 대문자로 입력야 함. ex) 실버 = SILVER
resolve #151

Feat: 티어 이름을 가지고 S3에서 티어별 이미지 URL 가져오는 기능 추가

---

src/main/resources/static/js/board-bookmark.js
src/main/resources/static/js/chat.js
src/main/resources/templates/board/board-bookmark.html
src/main/resources/templates/board/board-list.html
src/main/resources/templates/board/board-update-form.html
src/main/resources/templates/board/board-write-form.html
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/matching/chat.html
src/main/resources/templates/matching/matching.html
src/main/resources/templates/mypage.html
src/main/resources/templates/signup.html

- 기존 : [테마]
- 변경 후 : [테마] - Find My Duo

Style: 각 페이지의 테마에 맞게 Title 변경

---

src/main/java/com/idle/fmd/global/config/etc/WebClientConfig.java

- WebClientConfig.webClient()의 baseurl 유동적으로 변경
resolve #158

Fix: 158 Client 연결 오류 해결

---

src/main/resources/static/js/board-bookmark.js
src/main/resources/static/js/chat.js
src/main/resources/templates/board/board-bookmark.html
src/main/resources/templates/board/board-list.html
src/main/resources/templates/board/board-update-form.html
src/main/resources/templates/board/board-write-form.html
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/matching/chat.html
src/main/resources/templates/matching/matching.html
src/main/resources/templates/mypage.html
src/main/resources/templates/signup.html

- 기존 : [테마]
- 변경 후: [테마] - Find My Duo
resolve #155

Style: 각 페이지의 테마에 맞게 Title이 설정되도록 변경

---

src/main/java/com/idle/fmd/domain/board/controller/BoardViewController.java
src/main/java/com/idle/fmd/domain/chating/controller/ChatController.java

- BoardViewController, ChatController 반환 URL 수정 작업

Fix: ViewController 반환되는 URL 수정 작업

---

src/main/resources/static/js/board-update-form.js
src/main/resources/static/js/board-write-form.js
src/main/resources/static/js/login.js
src/main/resources/static/js/matching.js
src/main/resources/static/js/signup.js
src/main/resources/templates/board/board-update-form.html
src/main/resources/templates/board/board-write-form.html
src/main/resources/templates/login.html
src/main/resources/templates/matching/matching.html
src/main/resources/templates/signup.html

- 로그인 alert,
- 회원가입 alert,
- 게시글 작성 alert,
- 매칭 alert,
- 게시글 업데이트 alert 수정

Refactor: sweetalert2 라이브러리 추가, alert 창 수정

---

src/main/java/com/idle/fmd/domain/board/controller/BoardController.java
src/main/java/com/idle/fmd/domain/board/dto/ReportDto.java
src/main/resources/static/js/board.js
src/main/resources/static/js/matching.js
src/main/resources/static/js/signup.js
src/main/resources/templates/board/board.html

- ReportDto @NotBlank 삭제
- BoardController.reportBoard @Valid 삭제

Refactor: 신고, 댓글 삭제 alert 수정

---

src/main/java/com/idle/fmd/domain/user/controller/UserController.java
src/main/java/com/idle/fmd/domain/user/dto/UserLoginResponseDto.java
src/main/java/com/idle/fmd/domain/user/entity/CustomUserDetails.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/resources/static/css/style.css
src/main/resources/static/js/mypage.js
src/main/resources/templates/mypage.html

- 로그인 응답 Dto에 프로필 이미지 경로를 전달하도록 Controller 및 Service 로직 수정
- 마이페이지에서 정보 변경 시 로컬 스토리지에도 변경된 정보로 새로 설정하도록 수정
- 마이페이지 UI 개선

Design: 마이페이지 프론트  기능 수정 및 UI 개선

---

src/main/java/com/idle/fmd/domain/chating/controller/ChatController.java
src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
src/main/java/com/idle/fmd/domain/user/service/UserService.java
src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
src/main/java/com/idle/fmd/global/utils/FileHandler.java

Refactor: 회원가입시 기본 프로필 이미지로 저장 되도록 수정

---

src/main/java/com/idle/fmd/domain/lol/job/LolApiJob.java
src/main/resources/static/js/matching.js

- 기존 수락,거절 시간: 20초 -> 2분
- 채팅방 이동 후 매칭 페이지로 리다이렉트 되는 딜레이시간 5초 추가

Refactor: 배포 후 riot api키 확인 편의성을 위한 로그 추가, 매칭페이지에서 딜레이 시간 변경

---

src/main/resources/static/html/navbar.html
src/main/resources/static/js/board-list.js
src/main/resources/static/js/matching.js
src/main/resources/static/js/mypage.js
src/main/resources/static/js/navbar.js
src/main/resources/templates/board/board-list.html
src/main/resources/templates/mypage.html

- mypage.js 내 불필요한 코드 삭제,
- 마이페이지 정보 수정 성공,실패 alert 창 수정,
- 비밀번호 변경 성공,실패 alert 창 수정,
- 롤 계정 연동 시 로딩 alert, 계정 연동 성공,실패시 alert 창 수정,
- 프로필이미지 성공,실패 alert 창 수정,
- 회원탈퇴 성공, 실패 alert 창 수정,
- navbar 로그아웃 alert 창 수정

Refactor: mypage.js 내 alert 창 수정

---

src/main/resources/static/css/matching.css
src/main/resources/templates/matching/matching.html

- matching.html: UI 개선
- matching.css: 매칭 css 스타일 추가

Design: 매칭 UI 개선

---

src/main/resources/static/css/matching.css
src/main/resources/static/js/chat.js
src/main/resources/templates/matching/chat.html

- 채팅방 UI 개선
- 메시지를 보내면 아래에서 보내지도록 기능 수정

Design: 채팅방 UI 개선 및 기능 수정

---

src/main/java/com/idle/fmd/global/config/etc/RedisConfig.java

Fix: Redis 연결에 필요없는 코드 삭제

---

README.md

- 프로젝트 소개
- 핵심 기능
- 개발환경 및 사용기술
- erd
- 서비스 아키텍처

Docs: readme.md 작성
